# These are the sample yaml file.
services:
  - name: "GitHub"
    regex: "^gh[pousr]_[A-Za-z0-9_]{36}$"
    verify_url: "https://api.github.com/user"
    verify_method: "GET"
    headers:
      "Authorization": "token %s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_exists"
        key: "login"

  - name: "Stripe"
    regex: "^sk_live_[0-9a-zA-Z]{24}$"
    verify_url: "https://api.stripe.com/v1/balance"
    verify_method: "GET"
    headers:
      "Authorization": "Bearer %s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_not_empty"
        key: "available"

  - name: "Slack"
    regex: "^xox[baprs]-[0-9]{11}-[0-9]{11}-[0-9]{12}-[a-zA-Z0-9]{32}$"
    verify_url: "https://slack.com/api/auth.test"
    verify_method: "POST"
    headers:
      "Authorization": "Bearer %s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_value"
        key: "ok"
        value: "true"

  - name: "AWS"
    regex: "^AKIA[0-9A-Z]{16}$"
    verify_url: "https://sts.amazonaws.com/?Action=GetCallerIdentity&Version=2011-06-15"
    verify_method: "POST"
    headers:
      "Authorization": "AWS4-HMAC-SHA256 Credential=%s"
    validation:
      status_code: 200
      content_type: "text/xml"
      success_indicator:
        type: "contains_string"
        value: "<GetCallerIdentityResponse"

  - name: "Mailgun"
    regex: "^key-[0-9a-zA-Z]{32}$"
    verify_url: "https://api.mailgun.net/v3/domains"
    verify_method: "GET"
    headers:
      "Authorization": "Basic %s"
    validation:
      status_code: 200
      success_indicator:
        type: "status_code_only"

  - name: "Twitter"
    regex: "^[1-9][0-9]*-[0-9a-zA-Z]{40}$"
    verify_url: "https://api.twitter.com/1.1/account/verify_credentials.json"
    verify_method: "GET"
    headers:
      "Authorization": "Bearer %s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_exists"
        key: "screen_name"

  - name: "Twilio"
    regex: "^SK[0-9a-fA-F]{32}$"
    verify_url: "https://api.twilio.com/2010-04-01/Accounts.json"
    verify_method: "GET"
    headers:
      "Authorization": "Basic %s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_exists"
        key: "accounts"

  - name: "SendGrid"
    regex: "^SG\\.[a-zA-Z0-9_-]+\\.[a-zA-Z0-9_-]+$"
    verify_url: "https://api.sendgrid.com/v3/user/credits"
    verify_method: "GET"
    headers:
      "Authorization": "Bearer %s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_exists"
        key: "total"

  - name: "MailChimp"
    regex: "^[0-9a-f]{32}-us[0-9]{1,2}$"
    verify_url: "https://us1.api.mailchimp.com/3.0/"
    verify_method: "GET"
    headers:
      "Authorization": "apikey %s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_exists"
        key: "account_id"

  - name: "Heroku"
    regex: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    verify_url: "https://api.heroku.com/account"
    verify_method: "GET"
    headers:
      "Authorization": "Bearer %s"
      "Accept": "application/vnd.heroku+json; version=3"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_exists"
        key: "email"

  - name: "DigitalOcean"
    regex: "^[0-9a-fA-F]{64}$"
    verify_url: "https://api.digitalocean.com/v2/account"
    verify_method: "GET"
    headers:
      "Authorization": "Bearer %s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_exists"
        key: "account"

  - name: "CircleCI"
    regex: "^[0-9a-f]{40}$"
    verify_url: "https://circleci.com/api/v2/me"
    verify_method: "GET"
    headers:
      "Circle-Token": "%s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_exists"
        key: "id"

  - name: "Dropbox"
    regex: "^[a-zA-Z0-9_-]{64}$"
    verify_url: "https://api.dropboxapi.com/2/users/get_current_account"
    verify_method: "POST"
    headers:
      "Authorization": "Bearer %s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_exists"
        key: "account_id"

  - name: "NPM"
    regex: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    verify_url: "https://registry.npmjs.org/-/whoami"
    verify_method: "GET"
    headers:
      "Authorization": "Bearer %s"
    validation:
      status_code: 200
      content_type: "application/json"
      success_indicator:
        type: "json_key_exists"
        key: "username"